'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Admins
    Public Property ID As Integer
    Public Property Anr As String
    Public Property Name As String
    Public Property Vorname As String
    Public Property Email As String
    Public Property Password As String

    Public Overridable Property Fluege As ICollection(Of Fluege) = New HashSet(Of Fluege)

End Class
