'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FluegeToPassagier
    Public Property ID As Integer
    Public Property FlugID As Integer
    Public Property PasID As Integer

    Public Overridable Property Fluege As Fluege
    Public Overridable Property Passagiere As Passagiere

End Class
