'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fluege
    Public Property ID As Integer
    Public Property Flugziel As String
    Public Property Abflugsort As String
    Public Property Datum As Nullable(Of Date)
    Public Property Startzeitpunkt As Nullable(Of System.TimeSpan)
    Public Property Landung As String
    Public Property AnzahlPassagiere As Nullable(Of Integer) = 0
    Public Property PilotID As Nullable(Of Integer)

    Public Overridable Property Piloten As Piloten
    Public Overridable Property Passagiere As ICollection(Of Passagiere) = New HashSet(Of Passagiere)
    Public Overridable Property Admins As ICollection(Of Admins) = New HashSet(Of Admins)

End Class
