'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database1Entities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database1Entities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Admins() As DbSet(Of Admins)
    Public Overridable Property Fluege() As DbSet(Of Fluege)
    Public Overridable Property FluegeToPassagier() As DbSet(Of FluegeToPassagier)
    Public Overridable Property FlugToAdmin() As DbSet(Of FlugToAdmin)
    Public Overridable Property Passagiere() As DbSet(Of Passagiere)
    Public Overridable Property Piloten() As DbSet(Of Piloten)

End Class
